// Claude auth detection (0-modify: presence only, NEVER reads token values).
// Paths (verified findings §1): $CLAUDE_CONFIG_DIR or ~/.claude/.credentials.json (oauth) |
// ANTHROPIC_API_KEY | ANTHROPIC_AUTH_TOKEN+ANTHROPIC_BASE_URL (this machine, first-class) |
// settings.json.env | apiKeyHelper in settings.json
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { AuthProfile } from '../types';
import { resolveConfigDirectory, type ConfigDirectoryLocation } from '../config-location';

const CLAUDE_LOCATION = { envVar: 'CLAUDE_CONFIG_DIR', defaultSegments: ['.claude'] } as const;

export function resolveClaudeConfigLocation(
  configured?: string,
  env: NodeJS.ProcessEnv = process.env,
): ConfigDirectoryLocation {
  return resolveConfigDirectory(configured, CLAUDE_LOCATION, env);
}

export function resolveClaudeConfigDir(configured?: string, env: NodeJS.ProcessEnv = process.env): string {
  return resolveClaudeConfigLocation(configured, env).path;
}

/** Detect auth using the environment that the selected profile will expose to Claude. Passing
 * an explicit env is important for profile metadata: a daemon's native credential variables
 * must not make a different CLAUDE_CONFIG_DIR profile look like the native account. */
export function detectClaudeAuth(
  configuredDir?: string,
  env: NodeJS.ProcessEnv = process.env,
): AuthProfile {
  const profile: AuthProfile = { adapter: 'claude', mode: 'none', hasCredentials: false };
  profile.proxyDetected = !!(env.HTTPS_PROXY || env.HTTP_PROXY || env.ALL_PROXY);
  profile.baseUrlPresent = !!env.ANTHROPIC_BASE_URL;

  // 1. Explicit provider mode. These selectors take precedence over Anthropic credentials in
  // the same profile, matching profile discovery's established behavior.
  if (env.CLAUDE_CODE_USE_BEDROCK === '1' || env.CLAUDE_CODE_USE_VERTEX === '1') {
    profile.mode = 'providerKey';
    profile.hasCredentials = true;
    return profile;
  }
  // 2. ANTHROPIC_AUTH_TOKEN (+ optional BASE_URL) -- this machine's mode, first-class
  if (env.ANTHROPIC_AUTH_TOKEN) {
    profile.mode = 'authToken+BaseUrl';
    profile.hasCredentials = true;
    return profile;
  }
  // 3. ANTHROPIC_API_KEY
  if (env.ANTHROPIC_API_KEY) {
    profile.mode = 'apiKey';
    profile.hasCredentials = true;
    return profile;
  }
  const configDir = resolveClaudeConfigDir(configuredDir, env);
  const settingsPath = join(configDir, 'settings.json');
  let settings: { apiKeyHelper?: unknown; env?: Record<string, unknown> } | undefined;
  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, 'utf8')) as typeof settings;
    } catch {
      // best-effort
    }
  }

  // 4. Native settings.json env. Claude Code itself loads these values, so detection must use
  // the same source even when the detached moyu daemon did not inherit the caller's shell env.
  const settingsEnv = settings?.env;
  profile.baseUrlPresent ||= !!settingsEnv?.ANTHROPIC_BASE_URL;
  if (settingsEnv?.CLAUDE_CODE_USE_BEDROCK === '1' || settingsEnv?.CLAUDE_CODE_USE_VERTEX === '1') {
    profile.mode = 'providerKey';
    profile.hasCredentials = true;
    return profile;
  }
  if (settingsEnv?.ANTHROPIC_AUTH_TOKEN) {
    profile.mode = 'authToken+BaseUrl';
    profile.hasCredentials = true;
    return profile;
  }
  if (settingsEnv?.ANTHROPIC_API_KEY) {
    profile.mode = 'apiKey';
    profile.hasCredentials = true;
    return profile;
  }

  // 5. apiKeyHelper outranks OAuth sources in Claude Code's documented auth precedence.
  if (settings?.apiKeyHelper) {
    profile.mode = 'apiKey';
    profile.hasCredentials = true;
    return profile;
  }
  // 6. Long-lived OAuth token generated by `claude setup-token`. It may be supplied directly
  // or by the selected config directory's settings env, but its value is never returned.
  if (env.CLAUDE_CODE_OAUTH_TOKEN || settingsEnv?.CLAUDE_CODE_OAUTH_TOKEN) {
    profile.mode = 'oauth';
    profile.hasCredentials = true;
    return profile;
  }
  // 7. OAuth credentials file (presence only)
  const credPath = join(configDir, '.credentials.json');
  if (existsSync(credPath)) {
    try {
      const c = JSON.parse(readFileSync(credPath, 'utf8')) as Record<string, unknown>;
      if (c && (c.claudeAiOauth || c.anthropicApiKey || c.accessToken || c.apiKey)) {
        profile.mode = 'oauth';
        profile.hasCredentials = true;
        return profile;
      }
    } catch {
      // best-effort
    }
  }
  return profile;
}
